# Generated by Django 4.1.6 on 2023-02-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='Movie-thumbnail')),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('actor', models.CharField(blank=True, max_length=100, null=True)),
                ('writer', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'deactivate'), ('3', 'delete')], default=1, max_length=50)),
            ],
        ),
    ]
